# $Header: W:/Projects/OCL/rcs/OCLOBJ.INC 1.50 1996/08/11 23:47:06 B.STEIN Release $

ALLOBJ = \
.\OCL.obj \
.\OCLObject.obj \
.\clOString.obj \
.\O3State.obj \
.\OAuto3State.obj \
.\OAutoCheckBox.obj \
.\OAutoRadioButton.obj \
.\OApp.obj \
.\OAppBase.obj \
.\OBitmap.obj \
.\OBook.obj \
.\OBookPage.obj \
.\OBuffer.obj \
.\OButton.obj \
.\OButtonBar.obj \
.\OCheckBox.obj \
.\OCircSlider.obj \
.\OCollection.obj \
.\OCommand.obj \
.\OContainerBase.obj \
.\OCreate.obj \
.\OCriticalSec.obj \
.\ODate.obj \
.\ODialog.obj \
.\ODragEntryField.obj \
.\ODynamicLib.obj \
.\OEditor.obj \
.\OEntryField.obj \
.\OException.obj \
.\OFcl.obj \
.\OFillButton.obj\
.\OFrame.obj\
.\OGraphicsButton.obj\
.\OHelp.obj \
.\OHelpPopup.obj \
.\OIcon.obj \
.\OIndicator.obj \
.\OListBox.obj \
.\OLogo.obj \
.\OMemu.obj \
.\OMenu.obj \
.\OMenuItem.obj \
.\OMessage.obj \
.\OMLE.obj \
.\OMsgs.obj \
.\OMuxSem.obj \
.\OMuxWaitSem.obj \
.\ONPipe.obj \
.\ONSem.obj \
.\OOrderedCollection.obj \
.\OPicture.obj \
.\OPipe_istream.obj \
.\OPipe_ostream.obj \
.\OPipe_streamable.obj \
.\OPipeCli.obj \
.\OPipeSvr.obj \
.\OPipeTool.obj \
.\OPMException.obj \
.\OPMinit.obj \
.\OPMPipeTool.obj \
.\OProcStat.obj \
.\OProfile.obj \
.\OPushButton.obj \
.\ORadioButton.obj \
.\ORiffPlay.obj \
.\OScan.obj \
.\OSlider.obj \
.\OSpinBtn.obj \
.\OStatusLine.obj \
.\OString.obj \
.\OSysInfo.obj \
.\OSysInfoVio.obj \
.\OSysLevel.obj \
.\OThreadBase.obj \
.\OTimer.obj \
.\OUserButton.obj\
.\OValueSet.obj \
.\OVioApp.obj \
.\OVioException.obj \
.\OWinDefDlg.obj \
.\OWinDefWindow.obj \
.\OWindow.obj \
.\OXApp.obj \
.\OXcptBase.obj \
.\OXcptPM.obj \
.\OXcptVio.obj \
.\slOProcRecord.obj\
.\slOString.obj

OIPOBJ = \
.\OIP.obj \
.\OIP_Address.obj \
.\OIP_CliSocket.obj \
.\OIP_Host.obj \
.\OIP_SockAddress.obj \
.\OIP_Socket.obj \
.\OIP_SrvSocket.obj \
.\OIP_Server.obj \
.\OIP_Client.obj


OIPLIBOBJ = \
+.\OIP.obj \
+.\OIP_Address.obj \
+.\OIP_CliSocket.obj \
+.\OIP_Host.obj \
+.\OIP_SockAddress.obj \
+.\OIP_Socket.obj \
+.\OIP_SrvSocket.obj \
+.\OIP_Server.obj \
+.\OIP_Client.obj

LIBOBJ = \
+.\OCL.obj \
+.\OCLObject.obj \
+.\clOString.obj \
+.\O3State.obj \
+.\OAuto3State.obj \
+.\OAutoCheckBox.obj \
+.\OAutoRadioButton.obj \
+.\OApp.obj \
+.\OAppBase.obj \
+.\OBitmap.obj \
+.\OBook.obj \
+.\OBookPage.obj \
+.\OBuffer.obj \
+.\OButton.obj \
+.\OButtonBar.obj \
+.\OCheckBox.obj \
+.\OCircSlider.obj \
+.\OCollection.obj \
+.\OCommand.obj \
+.\OContainerBase.obj \
+.\OCreate.obj \
+.\OCriticalSec.obj \
+.\ODate.obj \
+.\ODialog.obj \
+.\ODragEntryField.obj \
+.\ODynamicLib.obj \
+.\OEditor.obj \
+.\OEntryField.obj \
+.\OException.obj \
+.\OFcl.obj \
+.\OFillButton.obj\
+.\OFrame.obj\
+.\OGraphicsButton.obj\
+.\OHelp.obj \
+.\OHelpPopup.obj \
+.\OIcon.obj \
+.\OIndicator.obj \
+.\OListBox.obj \
+.\OLogo.obj \
+.\OMemu.obj \
+.\OMenu.obj \
+.\OMenuItem.obj \
+.\OMessage.obj \
+.\OMLE.obj \
+.\OMsgs.obj \
+.\OMuxSem.obj \
+.\OMuxWaitSem.obj \
+.\ONPipe.obj \
+.\ONSem.obj \
+.\OOrderedCollection.obj \
+.\OPicture.obj \
+.\OPipe_istream.obj \
+.\OPipe_ostream.obj \
+.\OPipe_streamable.obj \
+.\OPipeCli.obj \
+.\OPipeSvr.obj \
+.\OPipeTool.obj \
+.\OPMException.obj \
+.\OPMinit.obj \
+.\OPMPipeTool.obj \
+.\OProcStat.obj \
+.\OProfile.obj \
+.\OPushButton.obj \
+.\ORadioButton.obj \
+.\ORiffPlay.obj \
+.\OScan.obj \
+.\OSlider.obj \
+.\OSpinBtn.obj \
+.\OStatusLine.obj \
+.\OString.obj \
+.\OSysInfo.obj \
+.\OSysInfoVio.obj \
+.\OSysLevel.obj \
+.\OThreadBase.obj \
+.\OTimer.obj \
+.\OUserButton.obj\
+.\OValueSet.obj \
+.\OVioApp.obj \
+.\OVioException.obj \
+.\OWinDefDlg.obj \
+.\OWinDefWindow.obj \
+.\OWindow.obj \
+.\OXApp.obj \
+.\OXcptBase.obj \
+.\OXcptPM.obj \
+.\OXcptVio.obj \
+.\slOProcRecord.obj \
+.\slOString.obj

METOBJ = \
.\OCL.obj\
.\OCLObject.obj\
.\clOString.obj\
.\O3State.obj\
.\OAuto3State.obj\
.\OAutoCheckBox.obj\
.\OAutoRadioButton.obj\
.\OApp.obj\
.\OAppBase.obj\
.\OBitmap.obj\
.\OBook.obj\
.\OBookPage.obj\
.\OBuffer.obj\
.\OButton.obj\
.\OButtonBar.obj\
.\OCheckBox.obj\
.\OCircSlider.obj\
.\OCollection.obj\
.\OCommand.obj\
.\OContainer.obj\
.\OContainerBase.obj\
.\OCreate.obj\
.\OCriticalSec.obj\
.\ODate.obj\
.\ODialog.obj\
.\ODragEntryField.obj\
.\ODynamicLib.obj\
.\OEditor.obj\
.\OEntryField.obj\
.\OException.obj\
.\OFcl.obj\
.\OFillButton.obj\
.\OFrame.obj\
.\OGraphicsButton.obj\
.\OHelp.obj\
.\OHelpPopup.obj\
.\OIcon.obj\
.\OIndicator.obj\
.\OListBox.obj\
.\OLogo.obj\
.\OMemu.obj\
.\OMenu.obj\
.\OMenuItem.obj\
.\OMessage.obj \
.\OMLE.obj\
.\OMsgs.obj\
.\OMuxSem.obj\
.\OMuxWaitSem.obj\
.\ONPipe.obj\
.\ONSem.obj\
.\OOrderedCollection.obj\
.\OPicture.obj\
.\OPipe_istream.obj\
.\OPipe_ostream.obj\
.\OPipe_streamable.obj\
.\OPipeCli.obj\
.\OPipeSvr.obj\
.\OPipeTool.obj\
.\OPMException.obj\
.\OPMinit.obj\
.\OPMPipeTool.obj\
.\OProcStat.obj\
.\OProfile.obj\
.\OPushButton.obj\
.\ORadioButton.obj\
.\ORiffPlay.obj\
.\OScan.obj\
.\OSlider.obj\
.\OSpinBtn.obj\
.\OStatusLine.obj\
.\OString.obj\
.\OSysInfo.obj\
.\OSysInfoVio.obj\
.\OSysLevel.obj\
.\OThreadBase.obj\
.\OTimer.obj\
.\OUserButton.obj\
.\OValueSet.obj\
.\OVioApp.obj\
.\OVioException.obj\
.\OWinDefDlg.obj\
.\OWinDefWindow.obj\
.\OWindow.obj\
.\OXApp.obj\
.\OXcptBase.obj\
.\OXcptPM.obj\
.\OXcptVio.obj\
.\slOProcRecord.obj\
.\slOString.obj
